// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaManager.Data;

#nullable disable

namespace NinjaManager.Migrations
{
    [DbContext(typeof(NinjaManagerDbContext))]
    [Migration("20241017164948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentModelNinjaModel", b =>
                {
                    b.Property<int>("InventoryEquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("NinjasNinjaId")
                        .HasColumnType("int");

                    b.HasKey("InventoryEquipmentId", "NinjasNinjaId");

                    b.HasIndex("NinjasNinjaId");

                    b.ToTable("EquipmentModelNinjaModel");
                });

            modelBuilder.Entity("NinjaManager.Models.EquipmentModel", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("GoldValue")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            Agility = 0,
                            Category = 0,
                            GoldValue = 10,
                            Intelligence = 0,
                            Name = "Headband",
                            Strength = 1
                        },
                        new
                        {
                            EquipmentId = 2,
                            Agility = 0,
                            Category = 2,
                            GoldValue = 20,
                            Intelligence = 1,
                            Name = "Jacket",
                            Strength = 2
                        },
                        new
                        {
                            EquipmentId = 3,
                            Agility = 1,
                            Category = 3,
                            GoldValue = 5,
                            Intelligence = 0,
                            Name = "Shuriken",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 4,
                            Agility = 0,
                            Category = 3,
                            GoldValue = 8,
                            Intelligence = 1,
                            Name = "Kunai",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 5,
                            Agility = 2,
                            Category = 2,
                            GoldValue = 15,
                            Intelligence = 0,
                            Name = "Weighted Clothes",
                            Strength = 3
                        },
                        new
                        {
                            EquipmentId = 6,
                            Agility = 3,
                            Category = 5,
                            GoldValue = 12,
                            Intelligence = 0,
                            Name = "Ninja Sandals",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 7,
                            Agility = 0,
                            Category = 1,
                            GoldValue = 25,
                            Intelligence = 3,
                            Name = "Necklace of Wisdom",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 8,
                            Agility = 0,
                            Category = 4,
                            GoldValue = 30,
                            Intelligence = 0,
                            Name = "Ring of Strength",
                            Strength = 4
                        },
                        new
                        {
                            EquipmentId = 9,
                            Agility = 0,
                            Category = 3,
                            GoldValue = 50,
                            Intelligence = 5,
                            Name = "Scroll of Healing",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 10,
                            Agility = 0,
                            Category = 3,
                            GoldValue = 100,
                            Intelligence = 0,
                            Name = "Blade of Destiny",
                            Strength = 10
                        });
                });

            modelBuilder.Entity("NinjaManager.Models.InventoryModel", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            EquipmentId = 1,
                            NinjaId = 1
                        },
                        new
                        {
                            InventoryId = 2,
                            EquipmentId = 2,
                            NinjaId = 1
                        },
                        new
                        {
                            InventoryId = 3,
                            EquipmentId = 3,
                            NinjaId = 1
                        },
                        new
                        {
                            InventoryId = 4,
                            EquipmentId = 4,
                            NinjaId = 1
                        },
                        new
                        {
                            InventoryId = 5,
                            EquipmentId = 1,
                            NinjaId = 2
                        },
                        new
                        {
                            InventoryId = 6,
                            EquipmentId = 5,
                            NinjaId = 2
                        },
                        new
                        {
                            InventoryId = 7,
                            EquipmentId = 6,
                            NinjaId = 2
                        },
                        new
                        {
                            InventoryId = 8,
                            EquipmentId = 2,
                            NinjaId = 3
                        },
                        new
                        {
                            InventoryId = 9,
                            EquipmentId = 7,
                            NinjaId = 3
                        },
                        new
                        {
                            InventoryId = 10,
                            EquipmentId = 2,
                            NinjaId = 4
                        },
                        new
                        {
                            InventoryId = 11,
                            EquipmentId = 8,
                            NinjaId = 4
                        },
                        new
                        {
                            InventoryId = 12,
                            EquipmentId = 1,
                            NinjaId = 5
                        },
                        new
                        {
                            InventoryId = 13,
                            EquipmentId = 3,
                            NinjaId = 5
                        },
                        new
                        {
                            InventoryId = 14,
                            EquipmentId = 9,
                            NinjaId = 5
                        },
                        new
                        {
                            InventoryId = 15,
                            EquipmentId = 1,
                            NinjaId = 6
                        },
                        new
                        {
                            InventoryId = 16,
                            EquipmentId = 6,
                            NinjaId = 6
                        },
                        new
                        {
                            InventoryId = 17,
                            EquipmentId = 5,
                            NinjaId = 6
                        },
                        new
                        {
                            InventoryId = 18,
                            EquipmentId = 4,
                            NinjaId = 7
                        },
                        new
                        {
                            InventoryId = 19,
                            EquipmentId = 2,
                            NinjaId = 7
                        },
                        new
                        {
                            InventoryId = 20,
                            EquipmentId = 10,
                            NinjaId = 8
                        },
                        new
                        {
                            InventoryId = 21,
                            EquipmentId = 1,
                            NinjaId = 9
                        },
                        new
                        {
                            InventoryId = 22,
                            EquipmentId = 7,
                            NinjaId = 9
                        },
                        new
                        {
                            InventoryId = 23,
                            EquipmentId = 1,
                            NinjaId = 10
                        },
                        new
                        {
                            InventoryId = 24,
                            EquipmentId = 2,
                            NinjaId = 10
                        },
                        new
                        {
                            InventoryId = 25,
                            EquipmentId = 3,
                            NinjaId = 10
                        });
                });

            modelBuilder.Entity("NinjaManager.Models.NinjaModel", b =>
                {
                    b.Property<int>("NinjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NinjaId"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NinjaId");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            NinjaId = 1,
                            Gold = 100,
                            Name = "Naruto Uzumaki"
                        },
                        new
                        {
                            NinjaId = 2,
                            Gold = 150,
                            Name = "Sasuke Uchiha"
                        },
                        new
                        {
                            NinjaId = 3,
                            Gold = 120,
                            Name = "Sakura Haruno"
                        },
                        new
                        {
                            NinjaId = 4,
                            Gold = 200,
                            Name = "Kakashi Hatake"
                        },
                        new
                        {
                            NinjaId = 5,
                            Gold = 90,
                            Name = "Rock Lee"
                        },
                        new
                        {
                            NinjaId = 6,
                            Gold = 110,
                            Name = "Neji Hyuga"
                        },
                        new
                        {
                            NinjaId = 7,
                            Gold = 130,
                            Name = "Tenten"
                        },
                        new
                        {
                            NinjaId = 8,
                            Gold = 250,
                            Name = "Orochimaru"
                        },
                        new
                        {
                            NinjaId = 9,
                            Gold = 160,
                            Name = "Hinata Hyuga"
                        },
                        new
                        {
                            NinjaId = 10,
                            Gold = 140,
                            Name = "Shino Aburame"
                        });
                });

            modelBuilder.Entity("EquipmentModelNinjaModel", b =>
                {
                    b.HasOne("NinjaManager.Models.EquipmentModel", null)
                        .WithMany()
                        .HasForeignKey("InventoryEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaManager.Models.NinjaModel", null)
                        .WithMany()
                        .HasForeignKey("NinjasNinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NinjaManager.Models.InventoryModel", b =>
                {
                    b.HasOne("NinjaManager.Models.EquipmentModel", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaManager.Models.NinjaModel", "Ninja")
                        .WithMany()
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });
#pragma warning restore 612, 618
        }
    }
}
