// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaManager.Data.Context;

#nullable disable

namespace NinjaManager.Data.Migrations
{
    [DbContext(typeof(NinjaManagerDbContext))]
    partial class NinjaManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaManager.Business.Models.EquipmentModel", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("GoldValue")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            Agility = 0,
                            Category = 0,
                            GoldValue = 10,
                            Intelligence = 0,
                            Name = "Headband",
                            Strength = 1
                        },
                        new
                        {
                            EquipmentId = 2,
                            Agility = 1,
                            Category = 0,
                            GoldValue = 50,
                            Intelligence = 0,
                            Name = "Steel Helmet",
                            Strength = 3
                        },
                        new
                        {
                            EquipmentId = 3,
                            Agility = 0,
                            Category = 0,
                            GoldValue = 100,
                            Intelligence = 2,
                            Name = "Golden Crown",
                            Strength = 5
                        },
                        new
                        {
                            EquipmentId = 4,
                            Agility = 0,
                            Category = 2,
                            GoldValue = 20,
                            Intelligence = 1,
                            Name = "Jacket",
                            Strength = 2
                        },
                        new
                        {
                            EquipmentId = 5,
                            Agility = 2,
                            Category = 2,
                            GoldValue = 15,
                            Intelligence = 0,
                            Name = "Weighted Clothes",
                            Strength = 3
                        },
                        new
                        {
                            EquipmentId = 6,
                            Agility = 1,
                            Category = 2,
                            GoldValue = 80,
                            Intelligence = 0,
                            Name = "Dragon Armor",
                            Strength = 8
                        },
                        new
                        {
                            EquipmentId = 7,
                            Agility = 1,
                            Category = 3,
                            GoldValue = 5,
                            Intelligence = 0,
                            Name = "Shuriken",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 8,
                            Agility = 0,
                            Category = 3,
                            GoldValue = 8,
                            Intelligence = 1,
                            Name = "Kunai",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 9,
                            Agility = 0,
                            Category = 3,
                            GoldValue = 100,
                            Intelligence = 0,
                            Name = "Blade of Destiny",
                            Strength = 10
                        },
                        new
                        {
                            EquipmentId = 10,
                            Agility = 3,
                            Category = 5,
                            GoldValue = 12,
                            Intelligence = 0,
                            Name = "Ninja Sandals",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 11,
                            Agility = 1,
                            Category = 5,
                            GoldValue = 30,
                            Intelligence = 0,
                            Name = "Steel Boots",
                            Strength = 2
                        },
                        new
                        {
                            EquipmentId = 12,
                            Agility = 5,
                            Category = 5,
                            GoldValue = 60,
                            Intelligence = 0,
                            Name = "Boots of Swiftness",
                            Strength = 1
                        },
                        new
                        {
                            EquipmentId = 13,
                            Agility = 0,
                            Category = 1,
                            GoldValue = 25,
                            Intelligence = 3,
                            Name = "Necklace of Wisdom",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 14,
                            Agility = 1,
                            Category = 1,
                            GoldValue = 40,
                            Intelligence = 1,
                            Name = "Amulet of Power",
                            Strength = 2
                        },
                        new
                        {
                            EquipmentId = 15,
                            Agility = 2,
                            Category = 1,
                            GoldValue = 70,
                            Intelligence = 5,
                            Name = "Silver Chain",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 16,
                            Agility = 0,
                            Category = 4,
                            GoldValue = 30,
                            Intelligence = 0,
                            Name = "Ring of Strength",
                            Strength = 4
                        },
                        new
                        {
                            EquipmentId = 17,
                            Agility = 0,
                            Category = 4,
                            GoldValue = 35,
                            Intelligence = 4,
                            Name = "Ring of Intelligence",
                            Strength = 0
                        },
                        new
                        {
                            EquipmentId = 18,
                            Agility = 4,
                            Category = 4,
                            GoldValue = 50,
                            Intelligence = 1,
                            Name = "Ring of Speed",
                            Strength = 0
                        });
                });

            modelBuilder.Entity("NinjaManager.Business.Models.InventoryModel", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("NinjaManager.Business.Models.NinjaModel", b =>
                {
                    b.Property<int>("NinjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NinjaId"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NinjaId");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            NinjaId = 1,
                            Gold = 100,
                            Name = "Naruto Uzumaki"
                        },
                        new
                        {
                            NinjaId = 2,
                            Gold = 150,
                            Name = "Sasuke Uchiha"
                        },
                        new
                        {
                            NinjaId = 3,
                            Gold = 120,
                            Name = "Sakura Haruno"
                        },
                        new
                        {
                            NinjaId = 4,
                            Gold = 200,
                            Name = "Kakashi Hatake"
                        },
                        new
                        {
                            NinjaId = 5,
                            Gold = 90,
                            Name = "Rock Lee"
                        },
                        new
                        {
                            NinjaId = 6,
                            Gold = 110,
                            Name = "Neji Hyuga"
                        },
                        new
                        {
                            NinjaId = 7,
                            Gold = 130,
                            Name = "Tenten"
                        },
                        new
                        {
                            NinjaId = 8,
                            Gold = 250,
                            Name = "Orochimaru"
                        },
                        new
                        {
                            NinjaId = 9,
                            Gold = 160,
                            Name = "Hinata Hyuga"
                        },
                        new
                        {
                            NinjaId = 10,
                            Gold = 140,
                            Name = "Shino Aburame"
                        });
                });

            modelBuilder.Entity("NinjaManager.Business.Models.InventoryModel", b =>
                {
                    b.HasOne("NinjaManager.Business.Models.EquipmentModel", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaManager.Business.Models.NinjaModel", "Ninja")
                        .WithMany("Inventory")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaManager.Business.Models.NinjaModel", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
